containerlab:
    schemaUrl: https://raw.githubusercontent.com/srl-labs/containerlab/refs/heads/main/schemas/clab.schema.json
    schemaFallback: ./data/clab.schema.json
    deviceConfig: ./data/device-config.json
fileSystem:
    storage: ./storage/
    run: ./run/
server:
    host: 127.0.0.1
    port: 3000
database:
    host: 127.0.0.1
    user: antimony
    database: antimony
    port: 5432
    localFile: ./test.db
auth:
    enableNative: true
    EnableOpenId: false
    openIdIssuer: ""
    openIdClientId: ""
    openIdAdminGroups: []
