server:
  # Default: 127.0.0.1
  host: 127.0.0.1
  # Default: 3000
  port: 3000
database:
  # Default: 127.0.0.1
  host: 127.0.0.1
  # Default: 5432
  port: 5432
storage:
  # Default: ./data/
  directory: ./data/
containerlab:
  # Default: https://raw.githubusercontent.com/srl-labs/containerlab/refs/heads/main/schemas/clab.schema.json
  schemaUrl: https://raw.githubusercontent.com/srl-labs/containerlab/refs/heads/main/schemas/clab.schema.json
  # Default: ./clab.schema.json
  schemaFallback: ./clab.schema.json