name: antimony-backend

services:
  backend:
    container_name: antimony-backend
    build:
      context: ./src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SB_MODE=dev
  db:
    container_name: antimony-backend-db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=antimony
      - POSTGRES_USER=antimony
      - POSTGRES_DB=antimony
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U antimony" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./.db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  keycloak-server:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./test/keycloak:/opt/keycloak/data/h2
    ports:
      - '4011:8080'