# https://taskfile.dev

version: '3'

tasks:
  clean:
    dir: '.'
    cmds:
      - sudo rm -rf ./build/
      - sudo rm -rf ./docker/

  lint:
    dir: './src'
    cmds:
      - golangci-lint run -c ../.golangci.yml

  build:
    dir: './src'
    cmds:
      - go tool swag init
      - go build -o ../build/antimony-server ./main.go
      - cp -r ../data/ ../build/
      - cp -r ../test/config.test.yml ../build/config.yml

  run:
    dir: './build'
    cmds:
      - task: build
      - sudo -E ./antimony-server -config=./config.yml
    env:
      SB_OIDC_SECRET: MHRymVDdv9t21ko4FGNGpXTvuLsjRtJd
      SB_DATABASE_PASSWORD: password123
      SB_NATIVE_USERNAME: admin
      SB_NATIVE_PASSWORD: admin

  build-docker:
    cmds:
      - cp -r ./data/ ./docker/
      - cp -r ./test/config.docker.yml ./docker/config.yml
      - sudo DOCKER_HOST=unix:///var/run/docker.sock docker build -t antimony-backend .

  run-docker:
    dir: './docker'
    cmds:
      - task: build-docker
      - sudo DOCKER_HOST=unix:///var/run/docker.sock docker run
          -e SB_NATIVE_USERNAME=admin
          -e SB_NATIVE_PASSWORD=admin
          -v ./db:/app/db
          -v ./storage:/app/storage/
          -v ./run:/app/run/
          -v ./data:/app/data
          -v ./config.yml:/app/config.yml
          -v /var/run/docker.sock:/var/run/docker.sock
          -p 3000:3000
          antimony-backend -sqlite=true -config=./config.yml

  swagger-docs:
    dir: './src'
    cmds:
      - go tool swag fmt
