name: Build backend and run tests

on:
  push:
    branches: [ development, main ]

  pull_request:
    branches: [ development, main ]

  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: src/go.mod
          cache-dependency-path: src/go.sum

      - name: Install Go Task
        uses: go-task/setup-task@v2
        with:
          version: 3.x

      - name: Run Linters
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: ./src
          args: -c ../.golangci.yml

      - name: Check Swagger docs are up to date
        run: task swag-check

      - name: Build
        working-directory: ./src
        run: task build

      - name: Run Test
        working-directory: ./src
        run: task test-race