name: Build backend and run tests

on:
  push:
    branches: [ development ]

  pull_request:
    branches: [ development ]

  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Run Linters
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ./src
          args: --config=lint-config.yml -c ../.golangci.yml

      - name: Build
        working-directory: ./src
        run: go build -v ./main.go

      - name: Run Test
        working-directory: ./src
        run: go test -v ./...