name: Build backend and run tests

on:
  push:
    branches: [ development ]

  pull_request:
    branches: [ development ]

  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Build
        working-directory: ./src
        run: go build -v ./main.go

#      - name: Run tests
#        working-directory: ./src
#        run: go rest -v ./main.go